'use client'
/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/uGCTBZKjqcD
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Bricolage_Grotesque } from 'next/font/google'
import { Cormorant_Garamond } from 'next/font/google'

bricolage_grotesque({
  subsets: ['latin'],
  display: 'swap',
})

cormorant_garamond({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { AvatarImage, AvatarFallback, Avatar } from "@/components/ui/avatar";
import {
  DropdownMenuTrigger,
  DropdownMenuItem,
  DropdownMenuSeparator,
  DropdownMenuContent,
  DropdownMenu,
} from "@/components/ui/dropdown-menu";
import {
  ContextMenuTrigger,
  ContextMenuItem,
  ContextMenuContent,
  ContextMenu,
} from "@/components/ui/context-menu";

export function VideoFeeds() {
  return (
    <div className="flex flex-col h-screen">
      <Header />
      <div className="flex flex-1">
        <nav className="bg-gray-900 text-white py-6 px-4 flex flex-col gap-4">
          <Button className="justify-start gap-2" size="sm" variant="ghost">
            <HomeIcon className="w-5 h-5" />
            Home
          </Button>
          <Button className="justify-start gap-2" size="sm" variant="ghost">
            <TrendingUpIcon className="w-5 h-5" />
            Trending
          </Button>
          <Button className="justify-start gap-2" size="sm" variant="ghost">
            <SubscriptIcon className="w-5 h-5" />
            Subscriptions
          </Button>
          <Button className="justify-start gap-2" size="sm" variant="ghost">
            <LibraryIcon className="w-5 h-5" />
            Library
          </Button>
        </nav>
        <div className="flex-1 bg-gray-100 dark:bg-gray-950 p-6">
          <div className="flex gap-2 overflow-x-auto pb-4">
            <Button className="whitespace-nowrap" size="sm" variant="ghost">
              All
            </Button>
            <Button className="whitespace-nowrap" size="sm" variant="ghost">
              Trending
            </Button>
            <Button className="whitespace-nowrap" size="sm" variant="ghost">
              Music
            </Button>
            <Button className="whitespace-nowrap" size="sm" variant="ghost">
              Gaming
            </Button>
            <Button className="whitespace-nowrap" size="sm" variant="ghost">
              News
            </Button>
            <Button className="whitespace-nowrap" size="sm" variant="ghost">
              Movies
            </Button>
            <Button className="whitespace-nowrap" size="sm" variant="ghost">
              Live
            </Button>
            <Button className="whitespace-nowrap" size="sm" variant="ghost">
              Sports
            </Button>
            <Button className="whitespace-nowrap" size="sm" variant="ghost">
              Learning
            </Button>
          </div>
          <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
            <div className="relative group">
              <ContextMenu>
                <ContextMenuTrigger className="absolute inset-0 z-10">
                  <span className="sr-only">Open context menu</span>
                </ContextMenuTrigger>
                <ContextMenuContent className="w-48">
                  <ContextMenuItem>
                    <ClockIcon className="w-4 h-4 mr-2" />
                    Save to Watch Later
                  </ContextMenuItem>
                  <ContextMenuItem>
                    <PlusIcon className="w-4 h-4 mr-2" />
                    Add to Playlist
                  </ContextMenuItem>
                  <ContextMenuItem>
                    <ShareIcon className="w-4 h-4 mr-2" />
                    Share
                  </ContextMenuItem>
                  <ContextMenuItem>
                    <FlagIcon className="w-4 h-4 mr-2" />
                    Report
                  </ContextMenuItem>
                </ContextMenuContent>
              </ContextMenu>
              <img
                alt="Video Thumbnail"
                className="w-full h-48 object-cover rounded-lg group-hover:opacity-50 transition-opacity"
                height={180}
                src="/placeholder.svg"
                style={{
                  aspectRatio: "320/180",
                  objectFit: "cover",
                }}
                width={320}
              />
              <div className="p-2">
                <h3 className="font-semibold text-base line-clamp-2">
                  Introducing the Frontend Cloud
                </h3>
                <div className="flex items-center gap-2 text-sm text-gray-500 dark:text-gray-400">
                  <div>Vercel</div>
                  <div>•</div>
                  <div>1.2M views</div>
                  <div>•</div>
                  <div>2 months ago</div>
                </div>
              </div>
            </div>
            <div className="relative group">
              <ContextMenu>
                <ContextMenuTrigger className="absolute inset-0 z-10">
                  <span className="sr-only">Open context menu</span>
                </ContextMenuTrigger>
                <ContextMenuContent className="w-48">
                  <ContextMenuItem>
                    <ClockIcon className="w-4 h-4 mr-2" />
                    Save to Watch Later
                  </ContextMenuItem>
                  <ContextMenuItem>
                    <PlusIcon className="w-4 h-4 mr-2" />
                    Add to Playlist
                  </ContextMenuItem>
                  <ContextMenuItem>
                    <ShareIcon className="w-4 h-4 mr-2" />
                    Share
                  </ContextMenuItem>
                  <ContextMenuItem>
                    <FlagIcon className="w-4 h-4 mr-2" />
                    Report
                  </ContextMenuItem>
                </ContextMenuContent>
              </ContextMenu>
              <img
                alt="Video Thumbnail"
                className="w-full h-48 object-cover rounded-lg group-hover:opacity-50 transition-opacity"
                height={180}
                src="/placeholder.svg"
                style={{
                  aspectRatio: "320/180",
                  objectFit: "cover",
                }}
                width={320}
              />
              <div className="p-2">
                <h3 className="font-semibold text-base line-clamp-2">
                  Vercel Ship Keynote: Introducing the frontend cloud
                </h3>
                <div className="flex items-center gap-2 text-sm text-gray-500 dark:text-gray-400">
                  <div>Vercel</div>
                  <div>•</div>
                  <div>70K subscribers</div>
                  <div>•</div>
                  <div>5 days ago</div>
                </div>
              </div>
            </div>
          </div>
          <div className="mt-8">
            <h2 className="text-xl font-bold mb-4">Shorts</h2>
            <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5 gap-4">
              <div className="relative group">
                <ContextMenu>
                  <ContextMenuTrigger className="absolute inset-0 z-10">
                    <span className="sr-only">Open context menu</span>
                  </ContextMenuTrigger>
                  <ContextMenuContent className="w-48">
                    <ContextMenuItem>
                      <ClockIcon className="w-4 h-4 mr-2" />
                      Save to Watch Later
                    </ContextMenuItem>
                    <ContextMenuItem>
                      <PlusIcon className="w-4 h-4 mr-2" />
                      Add to Playlist
                    </ContextMenuItem>
                    <ContextMenuItem>
                      <ShareIcon className="w-4 h-4 mr-2" />
                      Share
                    </ContextMenuItem>
                    <ContextMenuItem>
                      <FlagIcon className="w-4 h-4 mr-2" />
                      Report
                    </ContextMenuItem>
                  </ContextMenuContent>
                </ContextMenu>
                <img
                  alt="Shorts Thumbnail"
                  className="w-full h-[426px] object-cover rounded-lg group-hover:opacity-50 transition-opacity"
                  height={426}
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "240/426",
                    objectFit: "cover",
                  }}
                  width={240}
                />
                <div className="absolute bottom-2 right-2 bg-black/50 text-white px-2 py-1 rounded-full text-xs">
                  0:15
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

function ClockIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <polyline points="12 6 12 12 16 14" />
    </svg>
  );
}

function FlagIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M4 15s1-1 4-1 5 2 8 2 4-1 4-1V3s-1 1-4 1-5-2-8-2-4 1-4 1z" />
      <line x1="4" x2="4" y1="22" y2="15" />
    </svg>
  );
}

function HomeIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m3 9 9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z" />
      <polyline points="9 22 9 12 15 12 15 22" />
    </svg>
  );
}

function LibraryIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m16 6 4 14" />
      <path d="M12 6v14" />
      <path d="M8 8v12" />
      <path d="M4 4v16" />
    </svg>
  );
}

function PlusIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 12h14" />
      <path d="M12 5v14" />
    </svg>
  );
}

function SearchIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>
  );
}

function ShareIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M4 12v8a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-8" />
      <polyline points="16 6 12 2 8 6" />
      <line x1="12" x2="12" y1="2" y2="15" />
    </svg>
  );
}

function SignalIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M2 20h.01" />
      <path d="M7 20v-4" />
      <path d="M12 20v-8" />
      <path d="M17 20V8" />
      <path d="M22 4v16" />
    </svg>
  );
}

function SubscriptIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m4 5 8 8" />
      <path d="m12 5-8 8" />
      <path d="M20 19h-4c0-1.5.44-2 1.5-2.5S20 15.33 20 14c0-.47-.17-.93-.48-1.29a2.11 2.11 0 0 0-2.62-.44c-.42.24-.74.62-.9 1.07" />
    </svg>
  );
}

function TrendingUpIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polyline points="22 7 13.5 15.5 8.5 10.5 2 17" />
      <polyline points="16 7 22 7 22 13" />
    </svg>
  );
}

function UploadIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
      <polyline points="17 8 12 3 7 8" />
      <line x1="12" x2="12" y1="3" y2="15" />
    </svg>
  );
}

function YoutubeIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M2.5 17a24.12 24.12 0 0 1 0-10 2 2 0 0 1 1.4-1.4 49.56 49.56 0 0 1 16.2 0A2 2 0 0 1 21.5 7a24.12 24.12 0 0 1 0 10 2 2 0 0 1-1.4 1.4 49.55 49.55 0 0 1-16.2 0A2 2 0 0 1 2.5 17" />
      <path d="m10 15 5-3-5-3z" />
    </svg>
  );
}

export function Header({videocount, query, setQuery}) {
  return (
    <>
      <Head/>
      <div className="w-full bg-gray-100 dark:bg-gray-800 py-12 md:py-16 lg:py-24">
        <div className="container px-4 md:px-6">
          <div className="max-w-3xl mx-auto text-center space-y-4">
            <h1 className="text-3xl font-bold tracking-tight sm:text-4xl md:text-5xl">
              Discover the best videos
            </h1>
            <p className="text-gray-500 dark:text-gray-400 text-lg md:text-xl">
              Search, explore and download a vast collection of high-quality
              videos. <Link href={"/visualsitemap"}>-/\-</Link> - {videocount}+
              Videos
            </p>
            <div className="flex items-center max-w-xl mx-auto">
              <div className="relative flex-1">
                <SearchIcon className="absolute left-4 top-1/2 -translate-y-1/2 h-5 w-5 text-gray-400" />
                <Input
                  className="w-full rounded-l-md border-0 py-2 pl-12 pr-4 text-gray-900 dark:bg-gray-950 dark:text-gray-50 focus:ring-2 focus:ring-gray-500"
                  placeholder="Enter Terabox Link Here..."
                  type="search"
                  value={query}
                  onChange={(e) => setQuery(e.target.value)}
                />
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}


export const Head = () => {
  return <header className="bg-gray-900 text-white py-4 px-6 flex items-center justify-between">
  <div className="flex items-center gap-4">
    <Link className="flex items-center gap-2" href="/">
      <YoutubeIcon className="w-8 h-8 text-red-500" />
      <span className="text-xl font-bold">TeraDl</span>
    </Link>
    <form className="flex-1 max-w-md">
      <div className="relative">
        <Input
          className="bg-gray-800 text-white rounded-full pl-10 pr-4 py-2 w-full"
          placeholder="Search"
          type="text"
        />
        <SearchIcon className="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400" />
      </div>
    </form>
  </div>
  <div className="flex items-center gap-4">
    <Link href={"/new"}>
      <Button size="icon" variant="ghost">
        <UploadIcon className="w-6 h-6" />
        <span className="sr-only">Upload</span>
      </Button>
    </Link>
    <Link href={"https://teraboxdl-3xv9.onrender.com/"}>
      <Button size="icon" variant="ghost">
        <SignalIcon className="w-6 h-6" />
        <span className="sr-only">Notifications</span>
      </Button>
    </Link>
    <DropdownMenu>
      <DropdownMenuTrigger asChild>
        <Button size="icon" variant="ghost">
          <Avatar className="w-8 h-8 rounded-full">
            <AvatarImage alt="User Avatar" src="/placeholder-user.jpg" />
            <AvatarFallback>Try</AvatarFallback>
          </Avatar>
        </Button>
      </DropdownMenuTrigger>
      <DropdownMenuContent align="end">
        <DropdownMenuItem>
          If this site is not working try below listed sites
        </DropdownMenuItem>
        <DropdownMenuItem>
          <Link href={"https://teraboxdl-mu.vercel.app/"}>
            Teradl - 1 (vercel)
          </Link>
        </DropdownMenuItem>
        <DropdownMenuItem>
          <Link href={"https://teraboxdl-3xv9.onrender.com/"}>
            Teradl - 2 (render)
          </Link>
        </DropdownMenuItem>
        <DropdownMenuItem>Your channel</DropdownMenuItem>
        <DropdownMenuItem>YouTube Studio</DropdownMenuItem>
        <DropdownMenuItem>Switch account</DropdownMenuItem>
        <DropdownMenuSeparator />
        <DropdownMenuItem>Settings</DropdownMenuItem>
        <DropdownMenuItem>Help</DropdownMenuItem>
        <DropdownMenuItem>Sign out</DropdownMenuItem>
      </DropdownMenuContent>
    </DropdownMenu>
  </div>
</header>
}