/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/x7gLZNGw89W
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import Link from "next/link"

export function VideoSearch() {
  return (<>
    <div className="w-full bg-gray-100 dark:bg-gray-800 py-12 md:py-16 lg:py-24">
      <div className="container px-4 md:px-6">
        <div className="max-w-3xl mx-auto text-center space-y-4">
          <h1 className="text-3xl font-bold tracking-tight sm:text-4xl md:text-5xl">Discover the best videos</h1>
          <p className="text-gray-500 dark:text-gray-400 text-lg md:text-xl">
            Search and explore a vast collection of high-quality videos.
          </p>
          <form className="flex items-center max-w-xl mx-auto" >
            <div className="relative flex-1">
              <SearchIcon
                className="absolute left-4 top-1/2 -translate-y-1/2 h-5 w-5 text-gray-400" />
              <Input
                className="w-full rounded-l-md border-0 py-2 pl-12 pr-4 text-gray-900 dark:bg-gray-950 dark:text-gray-50 focus:ring-2 focus:ring-gray-500"
                placeholder="Search videos..."
                type="search" />
            </div>
            <Button className="rounded-r-md" type="submit">
              Search
            </Button>
          </form>
        </div>
      </div>
    </div>
    <div className="container px-4 md:px-6 py-12 md:py-16 lg:py-24">
      <h2 className="text-2xl font-bold tracking-tight mb-8">Trending Videos</h2>
      <div
        className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
        <div
          className="bg-white dark:bg-gray-950 rounded-lg overflow-hidden shadow-sm hover:shadow-md transition-shadow">
          <Link className="block" href="#">
            <img
              alt="Video Thumbnail"
              className="w-full aspect-video object-cover"
              height={225}
              src="/placeholder.svg"
              width={400} />
          </Link>
          <div className="p-4">
            <h3 className="text-lg font-semibold mb-2">
              <Link className="hover:underline" href="#">
                Introducing the Frontend Cloud
              </Link>
            </h3>
            <div className="flex items-center text-gray-500 dark:text-gray-400 text-sm">
              <UserIcon className="h-4 w-4 mr-2" />
              <span>Vercel</span>
              <span className="mx-2">•</span>
              <CalendarDaysIcon className="h-4 w-4 mr-2" />
              <span>2 months ago</span>
            </div>
          </div>
        </div>
        <div
          className="bg-white dark:bg-gray-950 rounded-lg overflow-hidden shadow-sm hover:shadow-md transition-shadow">
          <Link className="block" href="#">
            <img
              alt="Video Thumbnail"
              className="w-full aspect-video object-cover"
              height={225}
              src="/placeholder.svg"
              width={400} />
          </Link>
          <div className="p-4">
            <h3 className="text-lg font-semibold mb-2">
              <Link className="hover:underline" href="#">
                Vercel Ship Keynote: Introducing the frontend cloud
              </Link>
            </h3>
            <div className="flex items-center text-gray-500 dark:text-gray-400 text-sm">
              <UserIcon className="h-4 w-4 mr-2" />
              <span>Vercel</span>
              <span className="mx-2">•</span>
              <CalendarDaysIcon className="h-4 w-4 mr-2" />
              <span>5 months ago</span>
            </div>
          </div>
        </div>
        <div
          className="bg-white dark:bg-gray-950 rounded-lg overflow-hidden shadow-sm hover:shadow-md transition-shadow">
          <Link className="block" href="#">
            <img
              alt="Video Thumbnail"
              className="w-full aspect-video object-cover"
              height={225}
              src="/placeholder.svg"
              width={400} />
          </Link>
          <div className="p-4">
            <h3 className="text-lg font-semibold mb-2">
              <Link className="hover:underline" href="#">
                Using Vercel KV with Svelte
              </Link>
            </h3>
            <div className="flex items-center text-gray-500 dark:text-gray-400 text-sm">
              <UserIcon className="h-4 w-4 mr-2" />
              <span>Lee Robinson</span>
              <span className="mx-2">•</span>
              <CalendarDaysIcon className="h-4 w-4 mr-2" />
              <span>1 week ago</span>
            </div>
          </div>
        </div>
        <div
          className="bg-white dark:bg-gray-950 rounded-lg overflow-hidden shadow-sm hover:shadow-md transition-shadow">
          <Link className="block" href="#">
            <img
              alt="Video Thumbnail"
              className="w-full aspect-video object-cover"
              height={225}
              src="/placeholder.svg"
              width={400} />
          </Link>
          <div className="p-4">
            <h3 className="text-lg font-semibold mb-2">
              <Link className="hover:underline" href="#">
                Loading UI with Next.js 13
              </Link>
            </h3>
            <div className="flex items-center text-gray-500 dark:text-gray-400 text-sm">
              <UserIcon className="h-4 w-4 mr-2" />
              <span>Delba</span>
              <span className="mx-2">•</span>
              <CalendarDaysIcon className="h-4 w-4 mr-2" />
              <span>10 days ago</span>
            </div>
          </div>
        </div>
      </div>
    </div>
  </>);
}

function CalendarDaysIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <rect width="18" height="18" x="3" y="4" rx="2" ry="2" />
      <line x1="16" x2="16" y1="2" y2="6" />
      <line x1="8" x2="8" y1="2" y2="6" />
      <line x1="3" x2="21" y1="10" y2="10" />
      <path d="M8 14h.01" />
      <path d="M12 14h.01" />
      <path d="M16 14h.01" />
      <path d="M8 18h.01" />
      <path d="M12 18h.01" />
      <path d="M16 18h.01" />
    </svg>)
  );
}


function SearchIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>)
  );
}


function UserIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2" />
      <circle cx="12" cy="7" r="4" />
    </svg>)
  );
}
